{{- if .Values.global.generateIngressCertificates }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ .Release.namespace }}
  name: korifi-workloads-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.{{ .Values.global.defaultAppDomainName }}"
    tls:
      mode: SIMPLE
      credentialName: korifi-workloads-ingress-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: istio-system
spec:
  commonName: \*.{{ .Values.global.defaultAppDomainName }}
  dnsNames:
  - \*.{{ .Values.global.defaultAppDomainName }}
  issuerRef:
    kind: Issuer
    name: korifi-workloads-selfsigned-issuer
  secretName: {{ .Values.workloadsTLSSecret }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: korifi-workloads-selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
{{- end}}
